spring:
  application:
    name: data-feign
  #配置网关，由网关统一调度 http://xxx:9091/${application.name}/${methon}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
server:
  port: 8083

## 使用feign配合hystrix开启熔断功能
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

